### ISSUE TITLE
error on Spigot 1.8

### ISSUE THREAD

**Issue by matt4499** [matt4499/BanAnimations#1]
reporting error for: AlexLex
error:
```
Error occurred while enabling BanAnimations v2.2.0 (Is it up to date?)
java.lang.NoSuchFieldError: BEEF
at me.phantom.bananimations.animations.CageAnimation.<init>(CageAnimation.java:7) ~[?:?]
at me.phantom.bananimations.BanAnimations.animationHooks(BanAnimations.java:74) ~[?:?]
at me.phantom.bananimations.BanAnimations.onEnable(BanAnimations.java:50) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Spigot.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [Spigot.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [Spigot.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [Spigot.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [Spigot.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [Spigot.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [Spigot.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Spigot.jar:git-Spigot-e4d4710-e1ebe52]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

**Comment by matt4499** [comment]
You are using Spigot 1.8 which is HIGHLY outdated. Please use the newest version of paper, https://papermc.io/downloads
